export function expectedFreq(d: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9): number {
  return Math.log10(1 + 1 / d)
}

export function firstDigit(n: number): 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | null {
  if (!isFinite(n) || n === 0) return null
  const abs = Math.abs(n)
  const exp = Math.floor(Math.log10(abs))
  const d = Math.floor(abs / Math.pow(10, exp))
  if (d >= 1 && d <= 9) return d as 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
  // Fallback: floating-point imprecision at decade boundaries (e.g. 999999999999999)
  const fallback = parseInt(abs.toExponential()[0])
  return fallback >= 1 && fallback <= 9 ? (fallback as 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9) : null
}

export function distribution(nums: number[]): number[] {
  const counts = new Array(9).fill(0)
  let valid = 0
  for (const n of nums) {
    const d = firstDigit(n)
    if (d !== null) {
      counts[d - 1]++
      valid++
    }
  }
  return valid > 0 ? counts.map(c => c / valid) : counts
}

export function madScore(actual: number[]): number {
  if (actual.length !== 9) throw new RangeError(`madScore expects 9 values, got ${actual.length}`)
  let sum = 0
  for (let i = 0; i < 9; i++) {
    sum += Math.abs(actual[i] - expectedFreq((i + 1) as 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9))
  }
  return sum / 9
}

export function fitLabel(mad: number): 'Good' | 'Close' | 'Suspicious' {
  if (mad < 0.006) return 'Good'
  if (mad < 0.025) return 'Close'
  return 'Suspicious'
}

export type Dataset = {
  name: string
  description: string
  source: string
  unit: string
  n: number
  counts: number[]
  digits: number[] // length 9, index 0 = digit 1, fractions summing to ~1
  fetchedAt: string  // ISO 8601 timestamp of when the script ran
  queryCode: string  // exact query or computation used to collect the data
}

// Datasets are generated by scripts/process-benford-datasets.mjs from real sources.
// Do not edit digits/n manually — re-run the script instead.
import fibonacciData       from '../data/benford/fibonacci.json'
import powersOf2Data       from '../data/benford/powers-of-2.json'
import countryPopData      from '../data/benford/country-populations.json'
import countyPopData       from '../data/benford/us-county-populations.json'
import countryGdpData      from '../data/benford/country-gdps.json'
import countryAreaData     from '../data/benford/country-land-areas.json'
import cityPopData         from '../data/benford/us-city-populations.json'
import mountainsData       from '../data/benford/mountains.json'

export const DATASETS: Dataset[] = [
  fibonacciData,
  powersOf2Data,
  countryPopData,
  countyPopData,
  countryGdpData,
  countryAreaData,
  cityPopData,
  mountainsData,
] as Dataset[]
